### ISSUE TITLE
Publish hydrolysis-analyzer.html to npm

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-analyzer#212]
Using the npm package in the browser fails because not all files are included.

**Comment by cpboyd** [comment]
I'm not entirely sure if this is related to this specific issue, but with hydrolysis commit https://github.com/Polymer/hydrolysis/commit/e012ff0c18020d1b3d0d3c04f2883dbc028cf11f or later,  [vaadin/gwt-api-generator](https://github.com/vaadin/gwt-api-generator) fails with the following message:
```
module.js:338
    throw err;
    ^

Error: Cannot find module './lib/analyzer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\vgpe\node_modules\gwt-api-generator\node_modules\hydrolysis\index.js:17:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by garlicnation** [comment]
@cpboyd That issue is fixed in: https://github.com/Polymer/hydrolysis/pull/214

**Comment by rictic** [comment]
Closing as out of date
